import {
  MCPConfig,
  MCPSSEServer,
  MCPSHTTPServer,
  MCPStdioServer,
  SettingsValue,
} from "#/types/settings";
import type {
  MCPAuthCredential,
  MCPAuthValue,
  MCPAuthenticationConfig,
  MCPAuthenticationMetadataValue,
} from "#/types/mcp-auth";
import type { MCPServerConfig } from "#/types/mcp-server";

const EMPTY_MCP_CONFIG: MCPConfig = {
  sse_servers: [],
  stdio_servers: [],
  shttp_servers: [],
};

export const REDACTED_MCP_SECRET_VALUE = "<redacted>";

const LINEAR_DEPRECATED_SSE_URL = "https://mcp.linear.app/sse";
const LINEAR_SHTTP_URL = "https://mcp.linear.app/mcp";

/**
 * Linear removed its MCP SSE transport (the /sse endpoint rejects every
 * call since 2026-04-08). Detect persisted configs that still point at
 * the dead endpoint so they can be migrated to streamable HTTP at the
 * /mcp replacement. Matches only the exact deprecated URL (tolerating a
 * trailing slash or query string) — nothing else is rewritten.
 */
function isDeprecatedLinearSse(
  url: string,
  transport: string | undefined,
): boolean {
  if (transport !== "sse") return false;
  const normalized = url.split("?")[0].replace(/\/+$/, "");
  return normalized === LINEAR_DEPRECATED_SSE_URL;
}

type SdkMcpServerConfig = Record<string, SettingsValue | MCPAuthCredential>;
type SdkMcpConfig = { mcpServers: Record<string, SdkMcpServerConfig> };

/**
 * The dict key for an SSE/SHTTP server doubles as its display name once a
 * user provides one. Keys that match the auto-generated fallback pattern
 * (``sse``, ``shttp``, ``shttp_1``, …) emitted by {@link toSdkMcpConfig}
 * carry no user intent, so we surface them as "no name" — re-serializing
 * regenerates the identical fallback key and existing configs are left
 * untouched.
 */
function userGivenServerName(
  serverName: string,
  base: "sse" | "shttp",
): string | undefined {
  const autoGenerated = new RegExp(`^${base}(_\\d+)?$`);
  return autoGenerated.test(serverName) ? undefined : serverName;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === "object" && !Array.isArray(value);
}

function stringRecord(value: unknown): Record<string, string> | undefined {
  if (!isRecord(value)) return undefined;
  const entries = Object.entries(value).filter(
    (entry): entry is [string, string] => typeof entry[1] === "string",
  );
  return entries.length > 0 ? Object.fromEntries(entries) : undefined;
}

function hasRedactedStringLeaf(value: unknown): boolean {
  if (value === REDACTED_MCP_SECRET_VALUE) return true;
  if (Array.isArray(value)) return value.some(hasRedactedStringLeaf);
  if (isRecord(value)) return Object.values(value).some(hasRedactedStringLeaf);
  return false;
}

function getOAuthCredentials(
  value: unknown,
): Record<string, MCPAuthValue> | undefined {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return undefined;
  }
  return value as Record<string, MCPAuthValue>;
}

function normalizeTaggedAuthCredential(
  value: unknown,
): MCPAuthCredential | undefined {
  if (!isRecord(value)) return undefined;
  switch (value.strategy) {
    case "none":
      return { strategy: "none" };
    case "api_key":
      if (typeof value.value !== "string") return undefined;
      return {
        strategy: "api_key",
        value: value.value,
        ...(typeof value.header_name === "string" && {
          header_name: value.header_name,
        }),
      };
    case "bearer":
      if (typeof value.value !== "string") return undefined;
      return { strategy: "bearer", value: value.value };
    case "basic":
      if (
        typeof value.username !== "string" ||
        typeof value.password !== "string"
      ) {
        return undefined;
      }
      return {
        strategy: "basic",
        username: value.username,
        password: value.password,
      };
    case "header": {
      const headers = stringRecord(value.headers);
      return headers ? { strategy: "header", headers } : undefined;
    }
    case "oauth2": {
      const authentication = getAuthenticationConfig(value.authentication);
      const credentials = getOAuthCredentials(value.credentials);
      return {
        strategy: "oauth2",
        ...(authentication && { authentication }),
        ...(credentials && { credentials }),
      };
    }
    case "custom":
      return isRecord(value.fastmcp)
        ? {
            strategy: "custom",
            fastmcp: value.fastmcp as Record<string, MCPAuthValue>,
          }
        : undefined;
    default:
      return undefined;
  }
}

function authCredentialFromServerConfig(
  serverConfig: Record<string, unknown>,
): MCPAuthCredential | undefined {
  return normalizeTaggedAuthCredential(serverConfig.auth);
}

function getRemoteSecretFields(entry: {
  auth?: MCPAuthCredential;
  headers?: Record<string, string>;
}): Partial<SdkMcpServerConfig> {
  const fields: Partial<SdkMcpServerConfig> = {};
  if (entry.auth && !hasRedactedStringLeaf(entry.auth)) {
    fields.auth = entry.auth;
  }
  if (entry.headers && Object.keys(entry.headers).length > 0) {
    fields.headers = entry.headers;
  }
  return fields;
}

function getRemoteServerFields(server: MCPServerConfig) {
  return {
    ...(server.name && { name: server.name }),
    url: server.url!,
    ...(server.headers && { headers: server.headers }),
    ...(server.auth && { auth: server.auth }),
  };
}

export function toMcpSseServer(server: MCPServerConfig): MCPSSEServer {
  return getRemoteServerFields(server);
}

export function toMcpShttpServer(server: MCPServerConfig): MCPSHTTPServer {
  return {
    ...getRemoteServerFields(server),
    ...(server.timeout !== undefined && { timeout: server.timeout }),
  };
}

export function toMcpStdioServer(server: MCPServerConfig): MCPStdioServer {
  return {
    name: server.name!,
    command: server.command!,
    ...(server.args && { args: server.args }),
    ...(server.env && { env: server.env }),
  };
}

function getAuthenticationConfig(
  value: unknown,
): MCPAuthenticationConfig | undefined {
  if (!value || typeof value !== "object") return undefined;
  const record = value as Record<string, unknown>;
  if (record.type !== "oauth") return undefined;
  const authentication: MCPAuthenticationConfig = { type: "oauth" };
  if (
    record.client_auth_method === "none" ||
    record.client_auth_method === "client_secret_post" ||
    record.client_auth_method === "client_secret_basic"
  ) {
    authentication.client_auth_method = record.client_auth_method;
  }
  if (typeof record.scopes === "string") {
    authentication.scopes = record.scopes;
  } else if (
    Array.isArray(record.scopes) &&
    record.scopes.every((scope) => typeof scope === "string")
  ) {
    authentication.scopes = record.scopes;
  }
  if (typeof record.client_name === "string") {
    authentication.client_name = record.client_name;
  }
  if (typeof record.client_metadata_url === "string") {
    authentication.client_metadata_url = record.client_metadata_url;
  }
  if (
    record.additional_client_metadata &&
    typeof record.additional_client_metadata === "object" &&
    !Array.isArray(record.additional_client_metadata)
  ) {
    authentication.additional_client_metadata =
      record.additional_client_metadata as Record<
        string,
        MCPAuthenticationMetadataValue
      >;
  }
  return authentication;
}

/**
 * Parse an SDK mcp_config value ({ mcpServers: { ... } }) and convert it
 * to the frontend MCPConfig format used by UI components.
 */
export function parseMcpConfig(value: unknown): MCPConfig {
  if (!value || typeof value !== "object") {
    return { ...EMPTY_MCP_CONFIG };
  }

  const obj = value as Record<string, unknown>;

  if (
    !("mcpServers" in obj) ||
    !obj.mcpServers ||
    typeof obj.mcpServers !== "object"
  ) {
    return { ...EMPTY_MCP_CONFIG };
  }

  const sseServers: (string | MCPSSEServer)[] = [];
  const stdioServers: MCPStdioServer[] = [];
  const shttpServers: (string | MCPSHTTPServer)[] = [];
  // Legacy Linear SSE entries rewritten to the /mcp endpoint. Collected
  // separately and merged after the loop so an existing hand-added /mcp
  // entry (with its own auth/timeout) wins over the migrated one.
  const migratedShttpServers: MCPSHTTPServer[] = [];

  const mcpServers = obj.mcpServers as Record<string, Record<string, unknown>>;

  for (const [serverName, serverConfig] of Object.entries(mcpServers)) {
    if (!serverConfig || typeof serverConfig !== "object") continue;

    const url = serverConfig.url as string | undefined;

    if (url) {
      const transport = serverConfig.transport as string | undefined;
      const auth = authCredentialFromServerConfig(serverConfig);
      const headers = stringRecord(serverConfig.headers);

      if (isDeprecatedLinearSse(url, transport)) {
        const server: MCPSHTTPServer = { url: LINEAR_SHTTP_URL };
        if (auth) server.auth = auth;
        if (headers) server.headers = headers;
        migratedShttpServers.push(server);
      } else if (transport === "sse") {
        const name = userGivenServerName(serverName, "sse");
        const server: MCPSSEServer = { url };
        if (name) server.name = name;
        if (auth) server.auth = auth;
        if (headers) server.headers = headers;
        sseServers.push(server);
      } else {
        const name = userGivenServerName(serverName, "shttp");
        const server: MCPSHTTPServer = { url };
        if (name) server.name = name;
        if (serverConfig.timeout != null) {
          server.timeout = serverConfig.timeout as number;
        }
        if (auth) server.auth = auth;
        if (headers) server.headers = headers;
        shttpServers.push(server);
      }
    } else {
      const stdioServer: MCPStdioServer = {
        name: serverName,
        command: serverConfig.command as string,
      };
      if (serverConfig.args) {
        stdioServer.args = serverConfig.args as string[];
      }
      if (serverConfig.env) {
        stdioServer.env = serverConfig.env as Record<string, string>;
      }
      stdioServers.push(stdioServer);
    }
  }

  const normalizeUrl = (u: string) => u.replace(/\/+$/, "");
  for (const migrated of migratedShttpServers) {
    const alreadyPresent = shttpServers.some((entry) => {
      const entryUrl = typeof entry === "string" ? entry : entry.url;
      return normalizeUrl(entryUrl) === normalizeUrl(migrated.url);
    });
    if (!alreadyPresent) shttpServers.push(migrated);
  }

  return {
    sse_servers: sseServers,
    stdio_servers: stdioServers,
    shttp_servers: shttpServers,
  };
}

/**
 * Convert the frontend MCPConfig format back to the SDK { mcpServers: { ... } }
 * shape expected by agent_settings.mcp_config on the backend.
 *
 * Names are only suffixed (``_1``, ``_2``, …) when an earlier entry has
 * already claimed the bare base name. We intentionally do NOT use a single
 * monotonic counter across server types: that would, for example, rename a
 * stdio server "myname" to "myname_1" the moment any sse/shttp entry is
 * persisted ahead of it, and shift the suffix on every save as the count
 * of other server types changes. With per-base collision suffixing,
 * unrelated entries keep their human-meaningful names stable across edits.
 */
export function toSdkMcpConfig(config: MCPConfig): SdkMcpConfig | null {
  const mcpServers: Record<string, SdkMcpServerConfig> = {};

  const reserve = (base: string): string => {
    if (!(base in mcpServers)) return base;
    let i = 1;
    while (`${base}_${i}` in mcpServers) i += 1;
    return `${base}_${i}`;
  };

  for (const entry of config.sse_servers) {
    const server: SdkMcpServerConfig = {};
    let name: string | undefined;
    if (typeof entry === "string") {
      server.url = entry;
    } else {
      name = entry.name;
      server.url = entry.url;
      Object.assign(server, getRemoteSecretFields(entry));
    }
    server.transport = "sse";
    mcpServers[reserve(name || "sse")] = server;
  }

  for (const entry of config.shttp_servers) {
    const server: SdkMcpServerConfig = {};
    let name: string | undefined;
    if (typeof entry === "string") {
      server.url = entry;
    } else {
      name = entry.name;
      server.url = entry.url;
      Object.assign(server, getRemoteSecretFields(entry));
      if (entry.timeout != null) server.timeout = entry.timeout;
    }
    mcpServers[reserve(name || "shttp")] = server;
  }

  for (const entry of config.stdio_servers) {
    const server: SdkMcpServerConfig = {
      command: entry.command,
    };
    if (entry.args) server.args = entry.args;
    if (entry.env) server.env = entry.env;
    mcpServers[reserve(entry.name || "stdio")] = server;
  }

  return Object.keys(mcpServers).length > 0 ? { mcpServers } : null;
}
